spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: base
          uri: lb://center-server
          predicates:
            - Path=/*/sso/doLogin,/*/sso/login,/*/auth/**,/*/public/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
        - id: center
          uri: lb://center-server
          predicates:
            - Path=/center/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
        - id: web
          uri: lb://web-server
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
        - id: blog
          uri: lb://blog-server
          predicates:
            - Path=/blog/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
  redis:
    database: 15
