spring:
  output:
    ansi:
      enabled: always
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
    serialization:
      fail_on_empty_beans: false
  mvc:
    log-request-details: true
  redis:
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-active: 24
        max-idle: 12
    host: www.jydxl.link
    password: XLrootJYD713
  datasource:
    url: jdbc:p6spy:mysql://www.jydxl.link:3306/web?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: XLrootJYD713
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: hikari-cp
      max-lifetime: 1800000
      connection-test-query: select 1
  rabbitmq:
    username: root
    password: XLrootJYD713
    publisher-returns: true
    virtual-host: /
    host: www.jydxl.link
    port: 5672
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 0
    publisher-confirm-type: simple
  task:
    scheduling:
      pool:
        size: 12
    execution:
      pool:
        core-size: 12
        max-size: 24
        allow-core-thread-timeout: false
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://root:XLrootJYD713@www.jydxl.link:27017/mongo?authSource=admin
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
      rate: 10
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml, classpath*:mapper/**/*.xml

info:
  version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:logback.groovy

shiro:
  userNativeSessionManager: true
  loginUrl: /login
  sessionManager:
    cookie:
      name: token

shiro-redis:
  redis-manager:
    host: ${spring.redis.host}:${spring.redis.port}
    password: ${spring.redis.password}

dubbo:
  cloud:
    subscribed-services: web-server
  protocols:
    dubbo:
      port: -1
