spring:
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
    serialization:
      fail_on_empty_beans: false
  mvc:
    log-request-details: true
  redis:
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
    host: frp
    password: XLrootJYD713
    database: 0
  rabbitmq:
    username: root
    password: XLrootJYD713
    publisher-returns: true
    virtual-host: /
    host: frp
    port: 5672
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 0
    publisher-confirm-type: simple
  task:
    scheduling:
      pool:
        size: 16
    execution:
      pool:
        core-size: 16
        max-size: 32
        allow-core-thread-timeout: false
  data:
    mongodb:
      uri: mongodb://root:XLrootJYD713@frp:27017/mongo?authSource=admin
  thymeleaf:
    check-template-location: false
  zipkin:
    sender:
      type: rabbit
  #    base-url: http://frp:9411/
  sleuth:
    sampler:
      probability: 1.0
  #      rate: 10
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  kafka:
    bootstrap-servers: frp:9092
  elasticsearch:
    uris: [ http://frp:9200 ]

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml, classpath*:mappers/**/*.xml
  global-config:
    db-config:
      logic-delete-value: Y
      logic-not-delete-value: N
      logic-delete-field: deleted
#      update-strategy: ignored

info:
  version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    path: logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
  level:
    org:
      springframework:
        transaction: debug
        web: debug
      github: trace
    com:
      baomidou: debug
    io:
      netty: debug
      vertx: debug
    root: info

feign:
  okhttp:
    enabled: true

sa-token:
  timeout: 1800
  jwt-secret-key: XLrootJYD713
  token-name: token
  isShare: false
  maxLoginCount: 16
  alone-redis:
    database: 15
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    timeout: ${spring.redis.timeout}

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: org.github
  local:
    default:
      type: caffeine
      keyConvertor: jackson
      limit: 100
      expireAfterWriteInMillis: 100000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: jackson
      broadcastChannel: jetcache
      valueEncoder: kryo5
      valueDecoder: kryo5
      uri: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}/${spring.redis.database}

xxl:
  adminAddresses: http://frp:8080/xxl-job-admin
  accessToken: XLrootJYD713
  appname: ${spring.application.name}
  address:
  ip:
  port: 0
  logPath:
  logRetentionDays: 30

minio:
  url: http://frp:9000/
  accessKey: minio
  secretKey: XLrootJYD713
