spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.49
  instance:
    hostname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8761
