// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package org.github.module.file.common.dto.protobuf;

public final class FileProto {
  private FileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileDownloadReqProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileDownloadReqProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();
  }
  /**
   * Protobuf type {@code FileDownloadReqProto}
   */
  public static final class FileDownloadReqProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileDownloadReqProto)
      FileDownloadReqProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileDownloadReqProto.newBuilder() to construct.
    private FileDownloadReqProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileDownloadReqProto() {
      path_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileDownloadReqProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileDownloadReqProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadReqProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadReqProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto.class, org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto.Builder.class);
    }

    public static final int PATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object path_;
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(path_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto)) {
        return super.equals(obj);
      }
      org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto other = (org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto) obj;

      if (!getPath()
          .equals(other.getPath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileDownloadReqProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileDownloadReqProto)
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadReqProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadReqProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto.class, org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto.Builder.class);
      }

      // Construct using org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        path_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadReqProto_descriptor;
      }

      @java.lang.Override
      public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto getDefaultInstanceForType() {
        return org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto build() {
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto buildPartial() {
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto result = new org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto(this);
        result.path_ = path_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto) {
          return mergeFrom((org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto other) {
        if (other == org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto.getDefaultInstance()) return this;
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        path_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileDownloadReqProto)
    }

    // @@protoc_insertion_point(class_scope:FileDownloadReqProto)
    private static final org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto();
    }

    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileDownloadReqProto>
        PARSER = new com.google.protobuf.AbstractParser<FileDownloadReqProto>() {
      @java.lang.Override
      public FileDownloadReqProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileDownloadReqProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileDownloadReqProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileDownloadReqProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadReqProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileDownloadResProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileDownloadResProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 offset = 1;</code>
     * @return The offset.
     */
    long getOffset();

    /**
     * <code>int64 length = 2;</code>
     * @return The length.
     */
    long getLength();

    /**
     * <code>int32 pathLen = 3;</code>
     * @return The pathLen.
     */
    int getPathLen();

    /**
     * <code>string pathName = 4;</code>
     * @return The pathName.
     */
    java.lang.String getPathName();
    /**
     * <code>string pathName = 4;</code>
     * @return The bytes for pathName.
     */
    com.google.protobuf.ByteString
        getPathNameBytes();
  }
  /**
   * Protobuf type {@code FileDownloadResProto}
   */
  public static final class FileDownloadResProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileDownloadResProto)
      FileDownloadResProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileDownloadResProto.newBuilder() to construct.
    private FileDownloadResProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileDownloadResProto() {
      pathName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileDownloadResProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileDownloadResProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              offset_ = input.readInt64();
              break;
            }
            case 16: {

              length_ = input.readInt64();
              break;
            }
            case 24: {

              pathLen_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              pathName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadResProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadResProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto.class, org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto.Builder.class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private long offset_;
    /**
     * <code>int64 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private long length_;
    /**
     * <code>int64 length = 2;</code>
     * @return The length.
     */
    @java.lang.Override
    public long getLength() {
      return length_;
    }

    public static final int PATHLEN_FIELD_NUMBER = 3;
    private int pathLen_;
    /**
     * <code>int32 pathLen = 3;</code>
     * @return The pathLen.
     */
    @java.lang.Override
    public int getPathLen() {
      return pathLen_;
    }

    public static final int PATHNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object pathName_;
    /**
     * <code>string pathName = 4;</code>
     * @return The pathName.
     */
    @java.lang.Override
    public java.lang.String getPathName() {
      java.lang.Object ref = pathName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathName_ = s;
        return s;
      }
    }
    /**
     * <code>string pathName = 4;</code>
     * @return The bytes for pathName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathNameBytes() {
      java.lang.Object ref = pathName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offset_ != 0L) {
        output.writeInt64(1, offset_);
      }
      if (length_ != 0L) {
        output.writeInt64(2, length_);
      }
      if (pathLen_ != 0) {
        output.writeInt32(3, pathLen_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pathName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pathName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, offset_);
      }
      if (length_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, length_);
      }
      if (pathLen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pathLen_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pathName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pathName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto)) {
        return super.equals(obj);
      }
      org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto other = (org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto) obj;

      if (getOffset()
          != other.getOffset()) return false;
      if (getLength()
          != other.getLength()) return false;
      if (getPathLen()
          != other.getPathLen()) return false;
      if (!getPathName()
          .equals(other.getPathName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLength());
      hash = (37 * hash) + PATHLEN_FIELD_NUMBER;
      hash = (53 * hash) + getPathLen();
      hash = (37 * hash) + PATHNAME_FIELD_NUMBER;
      hash = (53 * hash) + getPathName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileDownloadResProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileDownloadResProto)
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadResProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadResProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto.class, org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto.Builder.class);
      }

      // Construct using org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        offset_ = 0L;

        length_ = 0L;

        pathLen_ = 0;

        pathName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.github.module.file.common.dto.protobuf.FileProto.internal_static_FileDownloadResProto_descriptor;
      }

      @java.lang.Override
      public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto getDefaultInstanceForType() {
        return org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto build() {
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto buildPartial() {
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto result = new org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto(this);
        result.offset_ = offset_;
        result.length_ = length_;
        result.pathLen_ = pathLen_;
        result.pathName_ = pathName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto) {
          return mergeFrom((org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto other) {
        if (other == org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto.getDefaultInstance()) return this;
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (other.getLength() != 0L) {
          setLength(other.getLength());
        }
        if (other.getPathLen() != 0) {
          setPathLen(other.getPathLen());
        }
        if (!other.getPathName().isEmpty()) {
          pathName_ = other.pathName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long offset_ ;
      /**
       * <code>int64 offset = 1;</code>
       * @return The offset.
       */
      @java.lang.Override
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>int64 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private long length_ ;
      /**
       * <code>int64 length = 2;</code>
       * @return The length.
       */
      @java.lang.Override
      public long getLength() {
        return length_;
      }
      /**
       * <code>int64 length = 2;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(long value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 length = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        
        length_ = 0L;
        onChanged();
        return this;
      }

      private int pathLen_ ;
      /**
       * <code>int32 pathLen = 3;</code>
       * @return The pathLen.
       */
      @java.lang.Override
      public int getPathLen() {
        return pathLen_;
      }
      /**
       * <code>int32 pathLen = 3;</code>
       * @param value The pathLen to set.
       * @return This builder for chaining.
       */
      public Builder setPathLen(int value) {
        
        pathLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pathLen = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPathLen() {
        
        pathLen_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pathName_ = "";
      /**
       * <code>string pathName = 4;</code>
       * @return The pathName.
       */
      public java.lang.String getPathName() {
        java.lang.Object ref = pathName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pathName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pathName = 4;</code>
       * @return The bytes for pathName.
       */
      public com.google.protobuf.ByteString
          getPathNameBytes() {
        java.lang.Object ref = pathName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pathName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pathName = 4;</code>
       * @param value The pathName to set.
       * @return This builder for chaining.
       */
      public Builder setPathName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pathName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pathName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPathName() {
        
        pathName_ = getDefaultInstance().getPathName();
        onChanged();
        return this;
      }
      /**
       * <code>string pathName = 4;</code>
       * @param value The bytes for pathName to set.
       * @return This builder for chaining.
       */
      public Builder setPathNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pathName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileDownloadResProto)
    }

    // @@protoc_insertion_point(class_scope:FileDownloadResProto)
    private static final org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto();
    }

    public static org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileDownloadResProto>
        PARSER = new com.google.protobuf.AbstractParser<FileDownloadResProto>() {
      @java.lang.Override
      public FileDownloadResProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileDownloadResProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileDownloadResProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileDownloadResProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.github.module.file.common.dto.protobuf.FileProto.FileDownloadResProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileDownloadReqProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileDownloadReqProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileDownloadResProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileDownloadResProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\"$\n\024FileDownloadReqProto\022\014\n\004" +
      "path\030\001 \001(\t\"Y\n\024FileDownloadResProto\022\016\n\006of" +
      "fset\030\001 \001(\003\022\016\n\006length\030\002 \001(\003\022\017\n\007pathLen\030\003 " +
      "\001(\005\022\020\n\010pathName\030\004 \001(\tB7\n*org.github.modu" +
      "le.file.common.dto.protobufB\tFileProtob\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FileDownloadReqProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileDownloadReqProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileDownloadReqProto_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_FileDownloadResProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileDownloadResProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileDownloadResProto_descriptor,
        new java.lang.String[] { "Offset", "Length", "PathLen", "PathName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
