management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: ubuntu:8848
    gateway:
      routes:
        - id: nacos-route
          uri: lb://service-gateway-provider
          predicates:
            - name: Path

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
    serialization:
      fail_on_empty_beans: false

server:
  port: 13650
