management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: ubuntu:8848
    gateway:
      routes:
        - id: web
          uri: lb://web-server
          predicates:
            - name: Path
              args:
                pattern: /web/**
          filters:
            - StripPrefix=1

server:
  port: 13650

logging:
  config: classpath:logback.groovy
