management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: ubuntu:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: lb://auth-server
          predicates:
            - Path=/*/login,/*/logout,/*/jsessionid,/*/jwt,/*/public/jwt
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: web
          uri: lb://web-server
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: client
          uri: lb://sub-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

server:
  port: 80

logging:
  config: classpath:logback.groovy
