spring:
  redis:
    port: 6380
    password: l
    timeout: 1s
    lettuce:
      pool:
        max-active: 16
        max-idle: 16
      shutdown-timeout: 1s
  datasource:
    url: jdbc:mysql://localhost:3357/security?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: l
    type: com.zaxxer.hikari.HikariDataSource
    jmx-enabled: true
    hikari:
      pool-name: hikari-mysql
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  profiles:
    active: dev
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
      enabled: true
      charset: utf-8
    log-request-details: true
    converters:
      preferred-json-mapper: jackson

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.github.base.entity

logging:
  level:
    web: debug
    org.github: debug
    io.netty: debug
