spring:
  redis:
    port: 6380
    password: l
    timeout: 10s
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
      shutdown-timeout: 10s
  datasource:
    url: jdbc:mysql://localhost:3357/security?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: l
    type: com.zaxxer.hikari.HikariDataSource
    jmx-enabled: true
    hikari:
      pool-name: hikari-mysql
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  profiles:
    active: dev
  http:
    encoding:
      force: true
      force-response: true
      force-request: true
      enabled: true
      charset: utf-8
    log-request-details: true
    converters:
      preferred-json-mapper: jackson
  task:
    scheduling:
      pool:
        size: 8
      thread-name-prefix: taskScheduler-
    execution:
      pool:
        core-size: 16
        max-size: 32
        allow-core-thread-timeout: false
      thread-name-prefix: taskExecutor-

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.github.base.entity

logging:
  level:
    web: trace
    sql: trace
    org.github: trace
    io.netty: trace
  file:
    max-history: 30
    max-size: 100MB
  path: ${user.dir}/logs
