spring:
  application:
    name: gradle-web
  output:
    ansi:
      enabled: always
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_absent
    serialization:
      fail_on_empty_beans: false
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
      enabled: true
      charset: utf-8
    log-request-details: true
    converters:
      preferred-json-mapper: jackson
  redis:
    port: 6380
    password: l
    timeout: 10s
    jedis:
      pool:
        max-active: 24
        max-idle: 12
    host: localhost
  datasource:
    url: jdbc:p6spy:mariadb://localhost:3306/security?useSSL=false
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: l
    type: com.zaxxer.hikari.HikariDataSource
    jmx-enabled: true
    name: hikari-mariadb
  rabbitmq:
    username: root
    password: l
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
    host: localhost
    port: 5672
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 0
  task:
    scheduling:
      pool:
        size: 12
    execution:
      pool:
        core-size: 12
        max-size: 24
        allow-core-thread-timeout: false
  data:
    redis:
      repositories:
        enabled: false

server:
  port: 8080

logging:
  level:
    web: trace
    sql: trace
    org.github: trace
    io.netty: trace
    io.vertx: trace
    org.springframework.transaction: trace
  file:
    max-history: 30
    max-size: 1GB
  path: ${user.home}/logs/${spring.application.name}/${info.version}/dev/

netty:
  config:
    port: 9002
    server: netty-server
    size: 24

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.github.**.entity

info:
  version: 0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    health-check-url-path: /actuator/health

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
