spring:
  redis:
    port: 6380
    password: l
    timeout: 10s
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
  datasource:
    url: jdbc:mariadb://localhost:3306/security?useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: l
    type: com.zaxxer.hikari.HikariDataSource
    jmx-enabled: true
    hikari:
      pool-name: hikari-mariadb
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_absent
    serialization:
      fail_on_empty_beans: false
  profiles:
    active: dev
  http:
    encoding:
      force: true
      force-response: true
      force-request: true
      enabled: true
      charset: utf-8
    log-request-details: true
    converters:
      preferred-json-mapper: jackson
  task:
    scheduling:
      pool:
        size: 8
    execution:
      pool:
        core-size: 16
        max-size: 32
        allow-core-thread-timeout: false
  rabbitmq:
    username: root
    password: l
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
    host: localhost
    port: 5672
  application:
    name: gradle-root
  output:
    ansi:
      enabled: always

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.github.**.entity

logging:
  level:
    web: trace
    sql: trace
    org.github: trace
    io.netty: trace
    io.vertx: trace
    org.springframework.transaction: trace

  file:
    max-history: 30
    max-size: 1GB
  path: ${user.dir}/logs
