package org.github.check

import com.google.common.collect.ImmutableMultiset
import com.google.common.collect.ImmutableMultiset.toImmutableMultiset
import org.github.ops.log
import org.github.ops.warn

fun main() {
  val versions = """Gradle: aopalliance:aopalliance:1.0
Gradle: cglib:cglib:3.1
Gradle: ch.qos.logback:logback-classic:1.2.11
Gradle: ch.qos.logback:logback-core:1.2.11
Gradle: cn.hutool:hutool-all:5.8.5
Gradle: co.elastic.clients:elasticsearch-java:7.17.4
Gradle: com.alibaba.cloud:spring-cloud-alibaba-commons:2.2.8.RELEASE
Gradle: com.alibaba.cloud:spring-cloud-alibaba-sentinel-datasource:2.2.8.RELEASE
Gradle: com.alibaba.cloud:spring-cloud-alibaba-sentinel-gateway:2.2.8.RELEASE
Gradle: com.alibaba.cloud:spring-cloud-circuitbreaker-sentinel:2.2.8.RELEASE
Gradle: com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:2.2.8.RELEASE
Gradle: com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.2.8.RELEASE
Gradle: com.alibaba.cloud:spring-cloud-starter-alibaba-seata:2.2.8.RELEASE
Gradle: com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel:2.2.8.RELEASE
Gradle: com.alibaba.csp:sentinel-annotation-aspectj:1.8.4
Gradle: com.alibaba.csp:sentinel-api-gateway-adapter-common:1.8.4
Gradle: com.alibaba.csp:sentinel-cluster-client-default:1.8.4
Gradle: com.alibaba.csp:sentinel-cluster-common-default:1.8.4
Gradle: com.alibaba.csp:sentinel-cluster-server-default:1.8.4
Gradle: com.alibaba.csp:sentinel-core:1.8.4
Gradle: com.alibaba.csp:sentinel-datasource-extension:1.8.4
Gradle: com.alibaba.csp:sentinel-datasource-nacos:1.8.4
Gradle: com.alibaba.csp:sentinel-parameter-flow-control:1.8.4
Gradle: com.alibaba.csp:sentinel-reactor-adapter:1.8.4
Gradle: com.alibaba.csp:sentinel-spring-cloud-gateway-adapter:1.8.4
Gradle: com.alibaba.csp:sentinel-spring-webflux-adapter:1.8.4
Gradle: com.alibaba.csp:sentinel-spring-webmvc-adapter:1.8.4
Gradle: com.alibaba.csp:sentinel-transport-common:1.8.4
Gradle: com.alibaba.csp:sentinel-transport-simple-http:1.8.4
Gradle: com.alibaba.csp:sentinel-zuul-adapter:1.8.4
Gradle: com.alibaba.fastjson2:fastjson2-extension:2.0.10
Gradle: com.alibaba.fastjson2:fastjson2:2.0.10
Gradle: com.alibaba.nacos:nacos-auth-plugin:2.1.0
Gradle: com.alibaba.nacos:nacos-client:2.1.0
Gradle: com.alibaba.nacos:nacos-encryption-plugin:2.1.0
Gradle: com.alibaba.spring:spring-context-support:1.0.11
Gradle: com.alibaba:fastjson:2.0.10
Gradle: com.auth0:java-jwt:4.0.0
Gradle: com.baomidou:dynamic-datasource-spring-boot-starter:3.5.1
Gradle: com.baomidou:mybatis-plus-annotation:3.5.2
Gradle: com.baomidou:mybatis-plus-boot-starter:3.5.2
Gradle: com.baomidou:mybatis-plus-core:3.5.2
Gradle: com.baomidou:mybatis-plus-extension:3.5.2
Gradle: com.baomidou:mybatis-plus-generator:3.5.3
Gradle: com.baomidou:mybatis-plus:3.5.2
Gradle: com.carrotsearch:hppc:0.8.1
Gradle: com.fasterxml.jackson.core:jackson-annotations:2.13.3
Gradle: com.fasterxml.jackson.core:jackson-core:2.13.3
Gradle: com.fasterxml.jackson.core:jackson-databind:2.13.3
Gradle: com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.13.3
Gradle: com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.13.3
Gradle: com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.13.3
Gradle: com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.3
Gradle: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.3
Gradle: com.fasterxml.jackson.datatype:jackson-datatype-guava:2.13.3
Gradle: com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.3
Gradle: com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.3
Gradle: com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.13.3
Gradle: com.fasterxml.jackson.module:jackson-module-kotlin:2.13.3
Gradle: com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.3
Gradle: com.fasterxml.jackson.module:jackson-module-scala_2.13:2.13.3
Gradle: com.fasterxml.woodstox:woodstox-core:6.2.7
Gradle: com.fasterxml:classmate:1.5.1
Gradle: com.github.ben-manes.caffeine:caffeine:3.1.1
Gradle: com.github.jsqlparser:jsqlparser:4.4
Gradle: com.github.luben:zstd-jni:1.5.0-4
Gradle: com.github.spullara.mustache.java:compiler:0.9.6
Gradle: com.google.code.findbugs:jsr305:3.0.2
Gradle: com.google.code.gson:gson:2.9.0
Gradle: com.google.errorprone:error_prone_annotations:2.14.0
Gradle: com.google.guava:failureaccess:1.0.1
Gradle: com.google.guava:guava:31.1-jre
Gradle: com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
Gradle: com.google.inject:guice:5.1.0
Gradle: com.google.j2objc:j2objc-annotations:1.3
Gradle: com.google.protobuf:protobuf-java-util:3.21.4
Gradle: com.google.protobuf:protobuf-java:3.21.4
Gradle: com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
Gradle: com.ibm.icu:icu4j:61.1
Gradle: com.jayway.jsonpath:json-path:2.7.0
Gradle: com.netflix.archaius:archaius-core:0.7.7
Gradle: com.netflix.hystrix:hystrix-core:1.4.3
Gradle: com.netflix.netflix-commons:netflix-commons-util:0.1.1
Gradle: com.netflix.netflix-commons:netflix-statistics:0.1.1
Gradle: com.netflix.ribbon:ribbon-core:2.3.0
Gradle: com.netflix.ribbon:ribbon-httpclient:2.3.0
Gradle: com.netflix.ribbon:ribbon-loadbalancer:2.3.0
Gradle: com.netflix.ribbon:ribbon-transport:2.3.0
Gradle: com.netflix.ribbon:ribbon:2.3.0
Gradle: com.netflix.servo:servo-core:0.10.1
Gradle: com.netflix.servo:servo-internal:0.10.1
Gradle: com.rabbitmq:amqp-client:5.14.2
Gradle: com.squareup.okhttp3:okhttp:4.10.0
Gradle: com.squareup.okio:okio-jvm:3.0.0
Gradle: com.squareup.retrofit2:retrofit:2.9.0
Gradle: com.stoyanr:evictor:1.0.0
Gradle: com.sun.jersey.contribs:jersey-apache-client4:1.19.1
Gradle: com.sun.jersey:jersey-client:1.19.1
Gradle: com.sun.jersey:jersey-core:1.19.1
Gradle: com.tdunning:t-digest:3.2
Gradle: com.thoughtworks.paranamer:paranamer:2.8
Gradle: com.typesafe.scala-logging:scala-logging_2.13:3.9.3
Gradle: com.typesafe:config:1.2.1
Gradle: com.vaadin.external.google:android-json:0.0.20131108.vaadin1
Gradle: com.yammer.metrics:metrics-core:2.2.0
Gradle: com.zaxxer:HikariCP:4.0.3
Gradle: commons-beanutils:commons-beanutils:1.9.4
Gradle: commons-cli:commons-cli:1.4
Gradle: commons-codec:commons-codec:1.15
Gradle: commons-collections:commons-collections:3.2.2
Gradle: commons-configuration:commons-configuration:1.8
Gradle: commons-fileupload:commons-fileupload:1.4
Gradle: commons-io:commons-io:2.11.0
Gradle: commons-lang:commons-lang:2.6
Gradle: commons-pool:commons-pool:1.6
Gradle: de.codecentric:spring-boot-admin-server-cloud:2.7.3
Gradle: de.codecentric:spring-boot-admin-server-ui:2.7.3
Gradle: de.codecentric:spring-boot-admin-server:2.7.3
Gradle: de.codecentric:spring-boot-admin-starter-server:2.7.3
Gradle: de.ruedigermoeller:fst:2.57
Gradle: io.dropwizard.metrics:metrics-core:4.2.10
Gradle: io.github.classgraph:classgraph:4.8.83
Gradle: io.github.openfeign.form:feign-form-spring:3.8.0
Gradle: io.github.openfeign.form:feign-form:3.8.0
Gradle: io.github.openfeign:feign-core:11.8
Gradle: io.github.openfeign:feign-slf4j:11.8
Gradle: io.lettuce:lettuce-core:6.1.9.RELEASE
Gradle: io.micrometer:micrometer-core:1.9.2
Gradle: io.netty:netty-all:4.1.79.Final
Gradle: io.netty:netty-buffer:4.1.79.Final
Gradle: io.netty:netty-codec-dns:4.1.79.Final
Gradle: io.netty:netty-codec-haproxy:4.1.79.Final
Gradle: io.netty:netty-codec-http2:4.1.79.Final
Gradle: io.netty:netty-codec-http:4.1.79.Final
Gradle: io.netty:netty-codec-memcache:4.1.79.Final
Gradle: io.netty:netty-codec-mqtt:4.1.79.Final
Gradle: io.netty:netty-codec-redis:4.1.79.Final
Gradle: io.netty:netty-codec-smtp:4.1.79.Final
Gradle: io.netty:netty-codec-socks:4.1.79.Final
Gradle: io.netty:netty-codec-stomp:4.1.79.Final
Gradle: io.netty:netty-codec-xml:4.1.79.Final
Gradle: io.netty:netty-codec:4.1.79.Final
Gradle: io.netty:netty-common:4.1.79.Final
Gradle: io.netty:netty-handler-proxy:4.1.79.Final
Gradle: io.netty:netty-handler:4.1.79.Final
Gradle: io.netty:netty-resolver-dns-classes-macos:4.1.79.Final
Gradle: io.netty:netty-resolver-dns:4.1.79.Final
Gradle: io.netty:netty-resolver:4.1.79.Final
Gradle: io.netty:netty-tcnative-boringssl-static:2.0.54.Final
Gradle: io.netty:netty-tcnative-classes:2.0.54.Final
Gradle: io.netty:netty-transport-classes-epoll:4.1.79.Final
Gradle: io.netty:netty-transport-classes-kqueue:4.1.79.Final
Gradle: io.netty:netty-transport-native-epoll:linux-aarch_64:4.1.79.Final
Gradle: io.netty:netty-transport-native-epoll:linux-x86_64:4.1.79.Final
Gradle: io.netty:netty-transport-native-unix-common:4.1.79.Final
Gradle: io.netty:netty-transport-rxtx:4.1.79.Final
Gradle: io.netty:netty-transport-sctp:4.1.79.Final
Gradle: io.netty:netty-transport-udt:4.1.79.Final
Gradle: io.netty:netty-transport:4.1.79.Final
Gradle: io.projectreactor.addons:reactor-extra:3.4.8
Gradle: io.projectreactor.netty:reactor-netty-core:1.0.21
Gradle: io.projectreactor.netty:reactor-netty-http:1.0.21
Gradle: io.projectreactor:reactor-core:3.4.21
Gradle: io.prometheus:simpleclient:0.15.0
Gradle: io.prometheus:simpleclient_tracer_common:0.15.0
Gradle: io.prometheus:simpleclient_tracer_otel:0.15.0
Gradle: io.prometheus:simpleclient_tracer_otel_agent:0.15.0
Gradle: io.reactivex:rxjava:1.3.8
Gradle: io.reactivex:rxnetty-contexts:0.4.9
Gradle: io.reactivex:rxnetty-servo:0.4.9
Gradle: io.reactivex:rxnetty:0.4.9
Gradle: io.seata:seata-all:1.5.2
Gradle: io.seata:seata-spring-autoconfigure-client:1.5.2
Gradle: io.seata:seata-spring-autoconfigure-core:1.5.2
Gradle: io.seata:seata-spring-boot-starter:1.5.2
Gradle: io.springfox:springfox-bean-validators:3.0.0
Gradle: io.springfox:springfox-boot-starter:3.0.0
Gradle: io.springfox:springfox-core:3.0.0
Gradle: io.springfox:springfox-data-rest:3.0.0
Gradle: io.springfox:springfox-oas:3.0.0
Gradle: io.springfox:springfox-schema:3.0.0
Gradle: io.springfox:springfox-spi:3.0.0
Gradle: io.springfox:springfox-spring-web:3.0.0
Gradle: io.springfox:springfox-spring-webflux:3.0.0
Gradle: io.springfox:springfox-spring-webmvc:3.0.0
Gradle: io.springfox:springfox-swagger-common:3.0.0
Gradle: io.springfox:springfox-swagger-ui:3.0.0
Gradle: io.springfox:springfox-swagger2:3.0.0
Gradle: io.swagger.core.v3:swagger-annotations:2.1.2
Gradle: io.swagger.core.v3:swagger-models:2.1.2
Gradle: io.swagger:swagger-annotations:1.5.20
Gradle: io.swagger:swagger-models:1.5.20
Gradle: io.vertx:vertx-auth-common:4.3.2
Gradle: io.vertx:vertx-bridge-common:4.3.2
Gradle: io.vertx:vertx-codegen:4.3.2
Gradle: io.vertx:vertx-core:4.3.2
Gradle: io.vertx:vertx-junit5:4.3.2
Gradle: io.vertx:vertx-lang-kotlin-coroutines:4.3.2
Gradle: io.vertx:vertx-lang-kotlin:4.3.2
Gradle: io.vertx:vertx-uri-template:4.3.2
Gradle: io.vertx:vertx-web-client:4.3.2
Gradle: io.vertx:vertx-web-common:4.3.2
Gradle: io.vertx:vertx-web:4.3.2
Gradle: io.zipkin.aws:brave-propagation-aws:0.21.3
Gradle: io.zipkin.brave:brave-context-slf4j:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-http:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-httpasyncclient:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-httpclient:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-jms:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-kafka-clients:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-kafka-streams:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-messaging:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-mongodb:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-rpc:5.13.9
Gradle: io.zipkin.brave:brave-instrumentation-spring-rabbit:5.13.9
Gradle: io.zipkin.brave:brave:5.13.9
Gradle: io.zipkin.reporter2:zipkin-reporter-brave:2.16.3
Gradle: io.zipkin.reporter2:zipkin-reporter-metrics-micrometer:2.16.3
Gradle: io.zipkin.reporter2:zipkin-reporter:2.16.3
Gradle: io.zipkin.reporter2:zipkin-sender-activemq-client:2.16.3
Gradle: io.zipkin.reporter2:zipkin-sender-amqp-client:2.16.3
Gradle: io.zipkin.reporter2:zipkin-sender-kafka:2.16.3
Gradle: io.zipkin.zipkin2:zipkin:2.23.2
Gradle: jakarta.activation:jakarta.activation-api:1.2.2
Gradle: jakarta.annotation:jakarta.annotation-api:1.3.5
Gradle: jakarta.json:jakarta.json-api:1.1.6
Gradle: jakarta.validation:jakarta.validation-api:2.0.2
Gradle: jakarta.xml.bind:jakarta.xml.bind-api:2.3.3
Gradle: javax.inject:javax.inject:1
Gradle: javax.servlet:javax.servlet-api:4.0.1
Gradle: javax.ws.rs:jsr311-api:1.1.1
Gradle: joda-time:joda-time:2.10.10
Gradle: mysql:mysql-connector-java:8.0.30
Gradle: net.bytebuddy:byte-buddy-agent:1.12.12
Gradle: net.bytebuddy:byte-buddy:1.12.12
Gradle: net.java.dev.jna:jna:5.10.0
Gradle: net.java.dev.jna:jna:5.12.1
Gradle: net.minidev:accessors-smart:2.4.8
Gradle: net.minidev:json-smart:2.4.8
Gradle: net.oschina.j2cache:j2cache-core:2.8.5-release
Gradle: net.sourceforge.argparse4j:argparse4j:0.7.0
Gradle: org.abego.treelayout:org.abego.treelayout.core:1.0.3
Gradle: org.antlr:antlr-runtime:3.5.2
Gradle: org.antlr:antlr4-runtime:4.8
Gradle: org.antlr:antlr4:4.8
Gradle: org.antlr:ST4:4.3
Gradle: org.apache.commons:commons-lang3:3.12.0
Gradle: org.apache.commons:commons-pool2:2.11.1
Gradle: org.apache.httpcomponents:httpasyncclient:4.1.5
Gradle: org.apache.httpcomponents:httpclient:4.5.13
Gradle: org.apache.httpcomponents:httpcore-nio:4.4.15
Gradle: org.apache.httpcomponents:httpcore:4.4.15
Gradle: org.apache.kafka:kafka-clients:3.1.1
Gradle: org.apache.kafka:kafka-clients:test:3.1.1
Gradle: org.apache.kafka:kafka-metadata:3.1.1
Gradle: org.apache.kafka:kafka-raft:3.1.1
Gradle: org.apache.kafka:kafka-server-common:3.1.1
Gradle: org.apache.kafka:kafka-storage-api:3.1.1
Gradle: org.apache.kafka:kafka-storage:3.1.1
Gradle: org.apache.kafka:kafka-streams-test-utils:3.1.1
Gradle: org.apache.kafka:kafka-streams:3.1.1
Gradle: org.apache.kafka:kafka_2.13:3.1.1
Gradle: org.apache.kafka:kafka_2.13:test:3.1.1
Gradle: org.apache.logging.log4j:log4j-api:2.17.2
Gradle: org.apache.logging.log4j:log4j-to-slf4j:2.17.2
Gradle: org.apache.lucene:lucene-analyzers-common:8.11.1
Gradle: org.apache.lucene:lucene-backward-codecs:8.11.1
Gradle: org.apache.lucene:lucene-core:8.11.1
Gradle: org.apache.lucene:lucene-grouping:8.11.1
Gradle: org.apache.lucene:lucene-highlighter:8.11.1
Gradle: org.apache.lucene:lucene-join:8.11.1
Gradle: org.apache.lucene:lucene-memory:8.11.1
Gradle: org.apache.lucene:lucene-misc:8.11.1
Gradle: org.apache.lucene:lucene-queries:8.11.1
Gradle: org.apache.lucene:lucene-queryparser:8.11.1
Gradle: org.apache.lucene:lucene-sandbox:8.11.1
Gradle: org.apache.lucene:lucene-spatial3d:8.11.1
Gradle: org.apache.lucene:lucene-suggest:8.11.1
Gradle: org.apache.shiro:shiro-cache:1.9.0
Gradle: org.apache.shiro:shiro-config-core:1.9.0
Gradle: org.apache.shiro:shiro-config-ogdl:1.9.0
Gradle: org.apache.shiro:shiro-core:1.9.0
Gradle: org.apache.shiro:shiro-crypto-cipher:1.9.0
Gradle: org.apache.shiro:shiro-crypto-core:1.9.0
Gradle: org.apache.shiro:shiro-crypto-hash:1.9.0
Gradle: org.apache.shiro:shiro-event:1.9.0
Gradle: org.apache.shiro:shiro-lang:1.9.0
Gradle: org.apache.shiro:shiro-spring-boot-starter:1.9.0
Gradle: org.apache.shiro:shiro-spring-boot-web-starter:1.9.0
Gradle: org.apache.shiro:shiro-spring:1.9.0
Gradle: org.apache.shiro:shiro-web:1.9.0
Gradle: org.apache.tomcat.embed:tomcat-embed-core:9.0.65
Gradle: org.apache.tomcat.embed:tomcat-embed-el:9.0.65
Gradle: org.apache.tomcat.embed:tomcat-embed-websocket:9.0.65
Gradle: org.apache.yetus:audience-annotations:0.5.0
Gradle: org.apache.zookeeper:zookeeper-jute:3.6.3
Gradle: org.apache.zookeeper:zookeeper:3.6.3
Gradle: org.apiguardian:apiguardian-api:1.1.2
Gradle: org.aspectj:aspectjrt:1.9.7
Gradle: org.aspectj:aspectjweaver:1.9.7
Gradle: org.assertj:assertj-core:3.22.0
Gradle: org.attoparser:attoparser:2.0.5.RELEASE
Gradle: org.bitbucket.b_c:jose4j:0.7.8
Gradle: org.bouncycastle:bcpkix-jdk15on:1.68
Gradle: org.bouncycastle:bcprov-jdk15on:1.68
Gradle: org.checkerframework:checker-qual:3.24.0
Gradle: org.codehaus.woodstox:stax2-api:4.2.1
Gradle: org.crazycake:shiro-redis-spring-boot-starter:3.3.1
Gradle: org.crazycake:shiro-redis:3.3.1
Gradle: org.eclipse.parsson:parsson:1.0.0
Gradle: org.elasticsearch.client:elasticsearch-rest-client:7.17.4
Gradle: org.elasticsearch.client:elasticsearch-rest-high-level-client:7.17.4
Gradle: org.elasticsearch.plugin:aggs-matrix-stats-client:7.17.4
Gradle: org.elasticsearch.plugin:lang-mustache-client:7.17.4
Gradle: org.elasticsearch.plugin:mapper-extras-client:7.17.4
Gradle: org.elasticsearch.plugin:parent-join-client:7.17.4
Gradle: org.elasticsearch.plugin:rank-eval-client:7.17.4
Gradle: org.elasticsearch:elasticsearch-cli:7.17.4
Gradle: org.elasticsearch:elasticsearch-core:7.17.4
Gradle: org.elasticsearch:elasticsearch-geo:7.17.4
Gradle: org.elasticsearch:elasticsearch-lz4:7.17.4
Gradle: org.elasticsearch:elasticsearch-plugin-classloader:7.17.4
Gradle: org.elasticsearch:elasticsearch-secure-sm:7.17.4
Gradle: org.elasticsearch:elasticsearch-x-content:7.17.4
Gradle: org.elasticsearch:elasticsearch:7.17.4
Gradle: org.freemarker:freemarker:2.3.31
Gradle: org.glassfish:javax.json:1.0.4
Gradle: org.hamcrest:hamcrest:2.2
Gradle: org.hdrhistogram:HdrHistogram:2.1.12
Gradle: org.hibernate.validator:hibernate-validator:6.2.3.Final
Gradle: org.javassist:javassist:3.29.0-GA
Gradle: org.jboss.byteman:byteman:4.0.19
Gradle: org.jboss.logging:jboss-logging:3.4.3.Final
Gradle: org.jetbrains.kotlin:kotlin-reflect:1.7.10
Gradle: org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10
Gradle: org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10
Gradle: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10
Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.7.10
Gradle: org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4
Gradle: org.jetbrains.kotlinx:kotlinx-coroutines-guava:1.6.4
Gradle: org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4
Gradle: org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.6.4
Gradle: org.jetbrains:annotations:13.0
Gradle: org.json:json:20211205
Gradle: org.junit.jupiter:junit-jupiter-api:5.8.2
Gradle: org.junit.jupiter:junit-jupiter-engine:5.8.2
Gradle: org.junit.jupiter:junit-jupiter-params:5.8.2
Gradle: org.junit.jupiter:junit-jupiter:5.8.2
Gradle: org.junit.platform:junit-platform-commons:1.8.2
Gradle: org.junit.platform:junit-platform-engine:1.8.2
Gradle: org.latencyutils:LatencyUtils:2.0.3
Gradle: org.lz4:lz4-java:1.8.0
Gradle: org.mapstruct:mapstruct:1.3.1.Final
Gradle: org.mockito:mockito-core:4.5.1
Gradle: org.mockito:mockito-junit-jupiter:4.5.1
Gradle: org.mongodb:bson-record-codec:4.6.1
Gradle: org.mongodb:bson:4.6.1
Gradle: org.mongodb:mongodb-driver-core:4.6.1
Gradle: org.mongodb:mongodb-driver-sync:4.6.1
Gradle: org.mybatis:mybatis-spring:2.0.7
Gradle: org.mybatis:mybatis:3.5.10
Gradle: org.objenesis:objenesis:3.3
Gradle: org.opentest4j:opentest4j:1.2.0
Gradle: org.ow2.asm:asm:9.3
Gradle: org.owasp.encoder:encoder:1.2.2
Gradle: org.postgresql:postgresql:42.4.1
Gradle: org.projectlombok:lombok:1.18.24
Gradle: org.reactivestreams:reactive-streams:1.0.4
Gradle: org.rocksdb:rocksdbjni:6.22.1.1
Gradle: org.scala-lang.modules:scala-collection-compat_2.13:2.4.4
Gradle: org.scala-lang.modules:scala-java8-compat_2.13:1.0.0
Gradle: org.scala-lang:scala-library:2.13.6
Gradle: org.scala-lang:scala-reflect:2.13.6
Gradle: org.skyscreamer:jsonassert:1.5.1
Gradle: org.slf4j:jul-to-slf4j:1.7.36
Gradle: org.slf4j:slf4j-api:1.7.36
Gradle: org.springframework.amqp:spring-amqp:2.4.6
Gradle: org.springframework.amqp:spring-rabbit:2.4.6
Gradle: org.springframework.boot:spring-boot-actuator-autoconfigure:2.7.2
Gradle: org.springframework.boot:spring-boot-actuator:2.7.2
Gradle: org.springframework.boot:spring-boot-autoconfigure:2.7.2
Gradle: org.springframework.boot:spring-boot-devtools:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-actuator:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-amqp:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-aop:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-cache:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-data-elasticsearch:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-data-mongodb:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-data-redis:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-jdbc:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-json:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-logging:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-reactor-netty:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-security:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-test:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-thymeleaf:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-tomcat:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-validation:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-web:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-webflux:2.7.2
Gradle: org.springframework.boot:spring-boot-starter-websocket:2.7.2
Gradle: org.springframework.boot:spring-boot-starter:2.7.2
Gradle: org.springframework.boot:spring-boot-test-autoconfigure:2.7.2
Gradle: org.springframework.boot:spring-boot-test:2.7.2
Gradle: org.springframework.boot:spring-boot:2.7.2
Gradle: org.springframework.cloud:spring-cloud-commons:3.1.3
Gradle: org.springframework.cloud:spring-cloud-context:3.1.3
Gradle: org.springframework.cloud:spring-cloud-gateway-server:3.1.3
Gradle: org.springframework.cloud:spring-cloud-loadbalancer:3.1.3
Gradle: org.springframework.cloud:spring-cloud-netflix-archaius:2.2.9.RELEASE
Gradle: org.springframework.cloud:spring-cloud-netflix-ribbon:2.2.9.RELEASE
Gradle: org.springframework.cloud:spring-cloud-openfeign-core:3.1.3
Gradle: org.springframework.cloud:spring-cloud-sleuth-api:3.1.3
Gradle: org.springframework.cloud:spring-cloud-sleuth-autoconfigure:3.1.3
Gradle: org.springframework.cloud:spring-cloud-sleuth-brave:3.1.3
Gradle: org.springframework.cloud:spring-cloud-sleuth-instrumentation:3.1.3
Gradle: org.springframework.cloud:spring-cloud-sleuth-zipkin:3.1.3
Gradle: org.springframework.cloud:spring-cloud-starter-bootstrap:3.1.3
Gradle: org.springframework.cloud:spring-cloud-starter-gateway:3.1.3
Gradle: org.springframework.cloud:spring-cloud-starter-loadbalancer:3.1.3
Gradle: org.springframework.cloud:spring-cloud-starter-netflix-archaius:2.2.9.RELEASE
Gradle: org.springframework.cloud:spring-cloud-starter-netflix-ribbon:2.2.9.RELEASE
Gradle: org.springframework.cloud:spring-cloud-starter-openfeign:3.1.3
Gradle: org.springframework.cloud:spring-cloud-starter-sleuth:3.1.3
Gradle: org.springframework.cloud:spring-cloud-starter:3.1.3
Gradle: org.springframework.data:spring-data-commons:2.7.2
Gradle: org.springframework.data:spring-data-elasticsearch:4.4.2
Gradle: org.springframework.data:spring-data-keyvalue:2.7.2
Gradle: org.springframework.data:spring-data-mongodb:3.4.2
Gradle: org.springframework.data:spring-data-redis:2.7.2
Gradle: org.springframework.kafka:spring-kafka-test:2.8.8
Gradle: org.springframework.kafka:spring-kafka:2.8.8
Gradle: org.springframework.plugin:spring-plugin-core:2.0.0.RELEASE
Gradle: org.springframework.plugin:spring-plugin-metadata:2.0.0.RELEASE
Gradle: org.springframework.retry:spring-retry:1.3.3
Gradle: org.springframework.security:spring-security-config:5.7.2
Gradle: org.springframework.security:spring-security-core:5.7.2
Gradle: org.springframework.security:spring-security-crypto:5.7.2
Gradle: org.springframework.security:spring-security-rsa:1.0.10.RELEASE
Gradle: org.springframework.security:spring-security-web:5.7.2
Gradle: org.springframework:spring-aop:5.3.22
Gradle: org.springframework:spring-beans:5.3.22
Gradle: org.springframework:spring-context-support:5.3.22
Gradle: org.springframework:spring-context:5.3.22
Gradle: org.springframework:spring-core:5.3.22
Gradle: org.springframework:spring-expression:5.3.22
Gradle: org.springframework:spring-jcl:5.3.22
Gradle: org.springframework:spring-jdbc:5.3.22
Gradle: org.springframework:spring-messaging:5.3.22
Gradle: org.springframework:spring-oxm:5.3.22
Gradle: org.springframework:spring-test:5.3.22
Gradle: org.springframework:spring-tx:5.3.22
Gradle: org.springframework:spring-web:5.3.22
Gradle: org.springframework:spring-webflux:5.3.22
Gradle: org.springframework:spring-webmvc:5.3.22
Gradle: org.springframework:spring-websocket:5.3.22
Gradle: org.t-io:tio-core:3.8.2.v20220628-RELEASE
Gradle: org.t-io:tio-utils:3.8.2.v20220628-RELEASE
Gradle: org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE
Gradle: org.thymeleaf:thymeleaf-spring5:3.0.15.RELEASE
Gradle: org.thymeleaf:thymeleaf:3.0.15.RELEASE
Gradle: org.unbescape:unbescape:1.1.6.RELEASE
Gradle: org.xerial.snappy:snappy-java:1.1.8.4
Gradle: org.xmlunit:xmlunit-core:2.9.0
Gradle: org.yaml:snakeyaml:1.30
Gradle: p6spy:p6spy:3.9.1
Gradle: redis.clients:jedis:4.2.3"""
  val multiset: ImmutableMultiset<String> = versions.split('\n').stream().map {it.substringBeforeLast(':')}.collect(toImmutableMultiset())
  multiset.forEachEntry {dep: String, count -> if (count > 1) log.warn {dep.substringAfter(':')}}
}

private val log = "main".log
