management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: admin-server
  cloud:
    nacos:
      discovery:
        server-addr: ubuntu:8848
  thymeleaf:
    check-template-location: false

server:
  port: 8000
