management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: admin-server
  cloud:
    nacos:
      discovery:
        server-addr: jydxl.link:8849,jydxl.link:8850,jydxl.link:8851
  thymeleaf:
    check-template-location: false

server:
  port: 9000

logging:
  file:
    path: logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
